version: '3.8'

services:
  api-nest:
    container_name: api-nest
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
      - '9229:9229'
    env_file:
      - .env
