services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres-db-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "16543:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - postgres-db-network

  api-nest:
    container_name: api-nest
    build:
        context: .
        target: development
    volumes:
        - .:/usr/src/app
    ports:
        - '${SERVER_PORT}:${SERVER_PORT}'
        - '9229:9229'
    env_file:
        - .env
  
  minio:
    image: docker.io/bitnami/minio:2022
    ports:
        - '9000:9000'
        - '9001:9001'
    networks:
        - minionetwork
    volumes:
        - 'minio_data:/data'
    environment:
        - MINIO_ROOT_USER=root
        - MINIO_ROOT_PASSWORD=Root@1234
        - MINIO_DEFAULT_BUCKETS=inventory-files

volumes:
  postgres-db-volume:
  minio_data:
      driver: local

networks:
  postgres-db-network:
    driver: bridge
  minionetwork:
    driver: bridge
